Dockerfile
library/k8s_status.py

Adds k8s_status module.
Fixes bug.

Add k8s_status Ansible module to build

---

.gitignore
bin/ao-logs
upstream.ubi7.Dockerfile

Bring upstream Dockerfile to ubi

---

Dockerfile
upstream.ubi7.Dockerfile

Add jmespath to dependencies

---

CHANGELOG.md
bin/entrypoint
bin/user_setup
ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
ci/dockerfiles/ansible.Dockerfile
images/scorecard-proxy/bin/entrypoint
images/scorecard-proxy/bin/user_setup
internal/scaffold/ansible/entrypoint.go
internal/scaffold/ansible/usersetup.go
internal/scaffold/entrypoint.go
internal/scaffold/entrypoint_test.go
internal/scaffold/helm/entrypoint.go
internal/scaffold/helm/usersetup.go
internal/scaffold/usersetup.go
internal/scaffold/usersetup_test.go
test/test-framework/build/bin/entrypoint
test/test-framework/build/bin/user_setup

Cherry-pick: https://github.com/operator-framework/operator-sdk/pull/2469/files
**Motivation**
https://bugzilla.redhat.com/show_bug.cgi?id=1793309
Bug 1793309

Bug 1793309: internal/scaffold: don't change /etc/passwd perms [release-4.3]

---

Dockerfile

Bug 1808102: Pin requests library to compatible version

---

internal/scaffold/helm/entrypoint.go
release/helm/bin/entrypoint

Resolves a merge issue that occurred during #34
Fix openshift/release#7420

internal/scaffold/helm/entrypoint.go: resolve merge issue

---

CHANGELOG.md
bin/entrypoint
bin/user_setup
ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
ci/dockerfiles/ansible.Dockerfile
go.mod
images/scorecard-proxy/bin/entrypoint
images/scorecard-proxy/bin/user_setup
internal/pkg/scaffold/ansible/entrypoint.go
internal/pkg/scaffold/ansible/usersetup.go
internal/pkg/scaffold/entrypoint.go
internal/pkg/scaffold/entrypoint_test.go
internal/pkg/scaffold/helm/entrypoint.go
internal/pkg/scaffold/helm/usersetup.go
internal/pkg/scaffold/usersetup.go
internal/pkg/scaffold/usersetup_test.go
test/test-framework/build/bin/entrypoint
test/test-framework/build/bin/user_setup

Cherry-pick: https://github.com/operator-framework/operator-sdk/pull/2469/files
**Motivation**
https://bugzilla.redhat.com/show_bug.cgi?id=1793308
Bug 1793308

Bug 1793308: internal/scaffold: don't change /etc/passwd perms [release-4.2]

---

CHANGELOG.md
bin/entrypoint
bin/user_setup
images/scorecard-proxy/bin/entrypoint
images/scorecard-proxy/bin/user_setup
internal/pkg/scaffold/ansible/entrypoint.go
internal/pkg/scaffold/ansible/usersetup.go
internal/pkg/scaffold/entrypoint.go
internal/pkg/scaffold/entrypoint_test.go
internal/pkg/scaffold/helm/entrypoint.go
internal/pkg/scaffold/helm/usersetup.go
internal/pkg/scaffold/usersetup.go
internal/pkg/scaffold/usersetup_test.go
upstream.Dockerfile

Cherry-pick of : https://github.com/operator-framework/operator-sdk/pull/2469/files
**Motivation**
https://bugzilla.redhat.com/show_bug.cgi?id=1793307
Bug 1793307

Bug 1793307: internal/scaffold: don't change /etc/passwd perms

---

release/ansible/upstream.Dockerfile

Fix install commands for ubi8

---

ci/dockerfiles/ansible-e2e-hybrid.Dockerfile

Fix install commands for ubi8 in ci dockerfiles

---

ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
internal/scaffold/ansible/dockerfilehybrid.go
release/ansible/upstream.Dockerfile

Remove hacks that made ubi7 + ubi8 work

---

ci/dockerfiles/ansible-molecule.Dockerfile

Add full source to /src in molecule image

---

release/ansible/Dockerfile.rhel8

Adds a Dockerfile compatible with RHEL 8 content.
A separate file is required, as the changes necessary for building with
RHEL 8 content are not compatible with RHEL 7.

Add Dockerfile.rhel8

---

OWNERS

Bug 1908461: Add bugzilla component to OWNERS file

---

patches/08-fix-downstream-stamps.patch

identification of downstream sdk
Signed-off-by: varshaprasad96 <varshaprasad96@gmail.com>
**Checklist**

Bug 1943698: patch - identification of downstream sdk

---

patches/08-fix-downstream-stamps.patch

Add identification of downstream SDK
**Checklist**

: Bug 1943699: patch - identification of downstream sdk

---

OWNERS_ALIASES

Signed-off-by: Catherine Chan-Tse <cchantse@redhat.com>
**Checklist**

Clean up admins

---

internal/plugins/openshift/v1/init.go

Bump OCP to 4.13 and UBI to 8.7.

OCPBUGS-11513: Bump OCP to 4.13 and UBI to 8.7.

---

internal/plugins/openshift/v1/init.go

Bump OCP to 4.14 and UBI to 8.8.

Bump OCP to 4.14 and UBI to 8.8

---

release/ansible/Dockerfile.rhel8

Update the Ansible Operator Dockerfile for RHEL8 to enable cachito based
on additional feedback.

Update Ansible Operator Dockerfile for cachito

---

internal/plugins/openshift/v1/init.go

Bump OCP version to 4.15
**Checklist**

OCPBUGS-23983: Update OCP to 4.15

---

.ci-operator.yaml
go.mod
release/ansible/Dockerfile.rhel8
release/helm/Dockerfile
release/sdk/Dockerfile

Combination of ART bump PRs to resolve test failures:
https://github.com/openshift/ocp-release-operator-sdk/pull/379
https://github.com/openshift/ocp-release-operator-sdk/pull/377
https://github.com/openshift/ocp-release-operator-sdk/pull/378
**Checklist**

OCPBUGS-34461,OCPBUGS-34327,OCPBUGS-34253: ART bumps

---

OWNERS_ALIASES

- Add CFE team members
Allow CFE team members to approve and merge PRs
**Checklist**

OCPBUGS-38333: Update admins to add CFE members

---

UPSTREAM-MERGE.sh

This PR updates the rebase script for creating a separate drop commit for vendor directory update
Previously the updates to the vendor directory was added to the merge commit used for merging the changes for the rebase. However, as the changes to the vendor directory should be added as a drop commit as per the norm used by openshift org while doing a rebase, this behaviour needed the change introduced in this PR.
**Checklist**

OCPBUGS-53052: UPSTREAM: <carry>: Update rebase script for creating separate drop commit for vendor directory update

---

OWNERS_ALIASES

This PR adds @mytreya-rh to the OWNERS file
Mytreya should have approval permission
**Checklist**

NO-JIRA: Add Mytreya to the OWNERS file
