openshift/ocp-release-operator-sdk

Dockerfile, bin/ao-logs
Adds a sidecar container to Ansible Operator deployments that aggregates the stdout of the ansible logs.
Currently looking at the ansible stdout log (what people are generally accustomed to seeing with Ansible) is a huge pain (you need to exec into a pod, and look at the stdout file in a very specific directory, `/tmp/ansible-operator/runner/{group}/{version}/{kind}/{namespace}/{name}/artifacts/{job id}/stdout`). This PR allows you to see the aggregated stdout without interfering with the machine readability of the standard operator logs.
- https://github.com/operator-framework/operator-sdk/pull/1193
=> add ansible logging aggregator

upstream.Dockerfile
Need to add a new way to build the upstream version of the ansible operator.
Ansible runner HTTP is not being packaged as RPM for upstream use. This means that we need to switch to pip to install these dependencies.
=> adding upstream docker file

Dockerfile
https://bugzilla.redhat.com/show_bug.cgi?id=1747376
=> Bug 1747376 - Fix tini path in downstream image

Dockerfile, ci/dockerfiles/ansible-e2e-hybrid.Dockerfile, ci/dockerfiles/ansible.Dockerfile, upstream.ubi7.Dockerfile
When we moved away from allowing CRI-O to handle builds, it looks like we didn't re-enable the user_setup script, which sets the permissions on /etc/passwd to prevent CRI-O from attempting to write to set it up.
=> Run user_setup script in builds

ci/tests/scaffolding/e2e-ansible-scaffold-hybrid.sh, ci/tests/scaffolding/e2e-helm-scaffold-hybrid.sh
Updates scaffolding for hybrid operator images so that branch resolution in `go.mod` is not required.
Since `-mod=vendor` is enabled, Go is unable to resolve a psuedo-version for the operator-sdk dependency. Since we use a `replace` line for operator-sdk anyway, we can set the `operator-sdk` require version to `v0.0.0`
=> ci/test/scaffolding: fix hybrid operator dependency resolution

Dockerfile, cmd/operator-sdk/build/cmd.go, upstream.Dockerfile, upstream.ubi7.Dockerfile
Specifying -x86_64-linux-gnu in the make target causes GOARCH=amd64 to
be defined, resulting in exec format errors when built on other arches.
CC: @crawford
=> Bug 1782996: Build natively on all arches

Makefile, release/helm/Dockerfile, release/helm/bin/entrypoint, release/helm/bin/user_setup, release/helm/upstream.Dockerfile
- Add helm Dockerfiles for OCP releases
- Add Makefile target to OCP release ci test
Create docker file for helm OKD and OCP downstream
**Local Test**
```
$ docker build -f release/helm/Dockerfile .
Sending build context to Docker daemon  116.6MB
Step 1/11 : FROM openshift/origin-release:golang-1.13 AS builder
---> 931fb4f9df6f
Step 2/11 : ENV GO111MODULE on GOFLAGS -mod=vendor
---> Using cache
---> 903304ef8374
Step 3/11 : COPY . /go/src/github.com/operator-framework/operator-sdk
---> Using cache
---> 31642428446d
Step 4/11 : RUN cd /go/src/github.com/operator-framework/operator-sdk  && make build/operator-sdk-dev VERSION=dev
---> Running in b82dfa37d44d
^Z
[3]+  Stopped                 docker build -f release/helm/Dockerfile …
```
=> add helm image release files

ci/dockerfiles/ansible-e2e.Dockerfile, ci/tests/e2e-ansible.sh, ci/tests/e2e-helm.sh, release/helm/Dockerfile
- Fix permissions for ocp ci tests
- Fix docker image for ocp release
- Fix order of delete of files for ansible
Errors in the OCP CI and to build helm docker image 
**NOTE**
Blocked  by the incident to pull image from `error: image "registry.svc.ci.openshift.org/ci-op-npnsk2i0/stable@sha256:595142acf537b1b17b8e340c2de6b73364c79034401d58f5b09dfbd6b742e5c8" `
checkout #incident-ci-registry  it's been mentioned multiple times there .
=> fix build and ci ocp for helm image

ci/dockerfiles/helm-e2e-hybrid.Dockerfile, ci/dockerfiles/helm-e2e.Dockerfile
Add the "/" in the path for charts 
Fix the following issue: 
```
{"level":"error","ts":1584242724.9947443,"logger":"cmd","msg":"Failed to create new manager factories.","Namespace":"default","error":"invalid chart directory helm-charts/nginx: stat helm-charts/nginx: no such file or directory","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/helm.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/helm/run.go:105\ngithub.com/operator-framework/operator-sdk/cmd/operator-sdk/execentrypoint.newRunHelmCmd.func1\n\tsrc/github.com/operator-framework/operator-sdk/cmd/operator-sdk/exe …
```
=> fix /ci/tests/e2e-helm.sh

ci/tests/e2e-helm.sh, ci/tests/scaffolding/e2e-helm-scaffold-hybrid.sh, ci/tests/scaffolding/e2e-helm-scaffold.sh
- Improve issues logs in the scripts called 
- ensure dir where the project should be scaffolded. (as done for ansible)
- update ci/tests/e2e-helm.sh  to use oc project default (as done for ansible)
Trying to solve:  https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/7420/rehearse-7420-pull-ci-openshift-ocp-release-operator-sdk-release-4.5-e2e-aws-helm/8/build-log.txt
=> small improvements fixes in the helm scripts used by the ci

release/ansible/Dockerfile.rhel8
Dockerfile.rhel8 had the older format before we split to use ansible-operator. This will fix the flag error from CI:
Error: unknown flag: --watches-file
=> Use ansible-operator binary not the operator-sdk

release/ansible/Dockerfile.rhel8, release/helm/Dockerfile
See #69 and #70 
It looks like those PRs need to be combined to get CI to pass.
=> Bug 1872080: Updating release/ansible/Dockerfile.rhel8 and release/helm/Dockerfile baseimages to match ocp-build-data config

release/ansible/Dockerfile.rhel8, release/helm/Dockerfile, release/sdk/Dockerfile
Combining PRs #76, #77, #80, #81, #83 since they are based on really old
branches with failing tests.
=> Updating o-e-(ansible|helm|sdk) builder & base images to be consistent with ART

patches/03-setversion.patch, release/sdk/Dockerfile
The operator-sdk version for downstream should not be v4.7.0 or dirty.
```
$ docker run -it --entrypoint=/bin/sh --user 1000:0 registry.build01.ci.openshift.org/ci-op-6qx8ss8d/stable:operator-sdk
sh-4.4$ operator-sdk version
operator-sdk version: "7ead15f5-dirty", commit: "7ead15f5713d34654270b7c9fb64ecedcd176d8e", kubernetes version: "v1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```
=> Bug 1915871: Fix the operator-sdk version on the image

ci/prow.Makefile, release/ansible/Dockerfile.rhel8, release/helm/Dockerfile
The ansible and helm operator binaries print out the openshift release version which will cause collisions with upstream versions. We want he version to match upstream with an added `ocp` tag to make it known this was an ocp build.
=> Bug 1917765: patch the Makefile before building ansible & helm operators

patches/04-bug1921458.patch, patches/05-handle-sub-pkg-name-mismatch.patch
`run bundle-upgrade` command handles error instead of throwing a panic, when a previous version of the operator bundle doesn't exist in the cluster 
```
Without installing etcd operator, 
Result:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1978d29]
```
Expected behavior: The command should check that the etcd operator doesn't exist in the cluster and handle the error gracefully instead of throwing a panic.
=> Bug 1921458: `run bundle-upgrade` should handle error gracefully when a previous operator version doesn't exist

patches/06-bug1924961-invalid-object-names.patch
* TrimDNS1123Label would trim strings but end up creating invalid DNS1123
strings.
* FormatOperatorNameDNS1123 would return strings that were invalid if
they begin or end with non-alphanumeric or hyphens.
Signed-off-by: jesus m. rodriguez <jmrodri@gmail.com>
=> Bug 1924961: Fixed invalid object names generated for long package names

internal/plugins/openshift/v1/init.go, internal/plugins/openshift/v1/init_test.go, internal/plugins/openshift/v1/plugin.go, internal/plugins/openshift/v1/suite_test.go, patches/11-openshiftv1-cli.patch
- internal/plugins/openshift: add OpenShift plugin to add OCP-specificconfiguration to projects
- internal/plugins/{go,ansible,helm}: run openshift/v1 phase 2 init plugin
**Motivation for the change:** some OCP-specific images need to be substituted for upstream ones. A phase 2 plugin accomplishes this for all plugins regardless of origin.
**Checklist**
=> Bug 1966759: OpenShift plugin adds OCP-specific configuration to projects

patches/11-openshiftv1-cli.patch
Update hybrid bundle to use openshift plugin and switch to downstream images.
Downstream plugins should use downstream images.
**Checklist**
=> Bug 2066615: run openshift plugin to get downstream images

ci/prow.Makefile, patches/14-bug2064408-use-ubi-for-untar.patch
Switch to using UBI instead of busybox for the untar image.
With the docker rate limiting in place, busybox is not a great choice
for the untar image. Therefore, switching to UBI to avoid that limit.
=> Bug 2064408: use ubi instead of busybox for untar image

ci/prow.Makefile, patches/14-bug2058044-use-ubi-for-untar.patch
Switch to using UBI instead of busybox for the untar image.
With the docker rate limiting in place, busybox is not a great choice
for the untar image. Therefore, switching to UBI to avoid that limit.
=> Bug 2058044: use ubi instead of busybox for untar image

patches/06-build-darwin-binary.patch, release/sdk/Dockerfile
Add darwin/arm64 to OCP operator-sdk artifacts.
The latest MacOS systems are being built with the ARM architecture.
**Checklist**
=> Add darwin/arm64 binaries

go.mod, go.sum, vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go, vendor/github.com/Masterminds/goutils/randomstringutils.go, vendor/github.com/Masterminds/goutils/stringutils.go, vendor/github.com/spf13/pflag/flag.go, vendor/modules.txt
Bump goutils dependency from v1.1.0 to v1.1.1
https://nvd.nist.gov/vuln/detail/CVE-2021-4238
**Checklist**
=> OCPBUGS-5613: Bump goutils dependency from v1.1.0 to v1.1.1 for CVE-2021-4238

patches/03-setversion.patch
Fixes `patches/03-setversion.patch` to have the correct version of `v1.30.0-ocp`
=> OCPBUGS-16138: fix 03-setversion.patch

internal/plugins/openshift/v1/init.go, internal/plugins/openshift/v1/init_test.go
- Adds image replacement for the hybrid helm plugin's scaffolded Dockerfile
- OCPBUGS-15801
=> OCPBUGS-15801: add image replacement for hybrid helm plugin Dockerfile

release/sdk/Dockerfile
Change base image of operator-sdk from rhel8 to rhel9
The operator-sdk release Dockerfile (https://github.com/openshift/ocp-release-operator-sdk/blob/2fcf5f0457f4aaccf3043cd99488b1d5050deada/release/sdk/Dockerfile) uses rhel9 based builder image, but uses rhel8 based base image. This may lead to version mismatch of GLIBC and end up in runtime error.
**Checklist**
=> OCPBUGS-38976: Change base image of operator-sdk from rhel8 to rhel9

Dockerfile
This PR removes the symlink of the Dockerfile to the removed `release/ansible/Dockerfile`. This file is unused and should be removed as it is causing image build issues.
=> OCPBUGS-37598: UPSTREAM: <carry>: Remove unused symlink of Dockerfile

internal/plugins/openshift/v1/init.go, internal/plugins/openshift/v1/init_test.go
Update base image of scaffolded Dockerfile for helm-operator to use rhel9 repository
The helm-operator image is using rhel9 base image from 4.16 onwards and discontinued publishing rhel8 based image. The repository also has changed from `registry.redhat.io/openshift4/ose-helm-operator` to `registry.redhat.io/openshift4/ose-helm-rhel9-operator`. This PR fixes the scaffolded Dockerfile for helm-operator to use the correct image.
**Checklist**
=> OCPBUGS-42425: Update base image of scaffolded Dockerfile for helm-operator to use rhel9 repository

internal/plugins/openshift/v1/init.go, internal/plugins/openshift/v1/init_test.go
Update base image of scaffolded Dockerfile for ansible-operator to use rhel9 repository
The ansible-operator image is using rhel9 base image from 4.17 onwards and discontinued publishing rhel8 based image. The repository also has changed from `registry.redhat.io/openshift4/ose-ansible-operator` to `registry.redhat.io/openshift4/ose-ansible-rhel9-operator`. This PR fixes the scaffolded Dockerfile for ansible-operator to use the correct image.
**Checklist**
=> OCPBUGS-42729: Update base image of scaffolded Dockerfile for ansible-operator to use rhel9 repository

internal/plugins/openshift/v1/init.go
Fix the release-4.18 ocpProductVersion
https://github.com/openshift/ocp-release-operator-sdk/pull/416/files#diff-fa5eae590fbd9f54ed4b66cdd4cc0c580ba0f62b7152b3c942c821ae42abc329 
<pre>
fail [/jenkins/workspace/ocp-common/ginkgo-test-vm/private/test/extended/operatorsdk/operatorsdk.go:4847]: Expected
<string>: # Build the manager binary
FROM registry.redhat.io/openshift4/ose-helm-rhel9-operator:v4.19
ENV HOME=/opt/helm
COPY watches.yaml ${HOME}/watches.yaml
COPY helm-charts  ${HOME}/helm-charts
WORKDIR ${HOME}
to contain substring
<string>: registry.redhat.io/openshift4/ose-helm-rhel9-operator:v4.18
</pre>
=> OCPBUGS-49323: Fix the release-4.18 ocpProductVersion

README.md, UPSTREAM-MERGE.sh
This PR updates the `UPSTREAM-MERGE.sh` to use the `main` branch instead of the `master` branch when no rebase branch input is provided.
The `master` branch will be renamed to `main`. This necessitates the update to the code which uses `master` branch explicitly.
**Checklist**
=> OCPBUGS-52398: UPSTREAM: <carry>: Use `main` branch instead of `master` branch
